import { Timestamp } from 'firebase/firestore';

export const ChatMessageData = [
  {
    id: 'msg_1',
    text: 'Say hii',
    senderId: 'user1Id',
    receiverId: 'user2Id',
    type: 'text',
    createdAt: Timestamp.fromMillis(Date.now() - 600000),
    status: 'seen',
  },
  {
    id: 'msg_2',
    text: 'Hello! 👋',
    senderId: 'user2Id',
    receiverId: 'user1Id',
    type: 'text',
    createdAt: Timestamp.fromMillis(Date.now() - 500000),
    status: 'seen',
  },
  {
    id: 'msg_3',
    text: 'How are you?',
    senderId: 'user1Id',
    receiverId: 'user2Id',
    type: 'text',
    createdAt: Timestamp.fromMillis(Date.now() - 400000),
    status: 'delivered',
  },
  {
    id: 'msg_4',
    type: 'image',
    imageUrl: 'https://firebase.storage/image_123.jpg',
    caption: 'Check this out',
    senderId: 'user2Id',
    receiverId: 'user1Id',
    createdAt: Timestamp.fromMillis(Date.now() - 300000),
    status: 'seen',
  },
  {
    id: 'msg_5',
    type: 'audio',
    audioUrl: 'https://firebase.storage/audio_456.mp3',
    duration: 12,
    senderId: 'user1Id',
    receiverId: 'user2Id',
    createdAt: Timestamp.fromMillis(Date.now() - 200000),
    status: 'sent',
  },
  {
    id: 'msg_6',
    text: 'Nice photo 😍',
    senderId: 'user1Id',
    receiverId: 'user2Id',
    type: 'text',
    createdAt: Timestamp.fromMillis(Date.now() - 100000),
    status: 'sent',
  },
  {
    id: 'msg_7',
    type: 'system',
    text: 'user2 joined the chat',
    createdAt: Timestamp.fromMillis(Date.now() - 900000),
  },
];
